_target_: pytorch_lightning.Trainer

max_epochs: -1
max_steps: 2000000
gradient_clip_val: 0
num_nodes: 1
benchmark: False
overfit_batches: 0.0
limit_train_batches: 1.0
check_val_every_n_epoch: 1
min_epochs: 1
log_every_n_steps: 50
max_time: null
accelerator: "gpu" #cpu, gpu or mps
devices: 1
detect_anomaly: False
precision: 32
profiler: null