# @package _global_

defaults:
  - _self_
  - data: default.yaml
  - ae: noiseband.yaml
  - loss: spec.yaml
  - trainer: default.yaml
  - exp: null
  - sweep: null

name: null
sample_rate: 48000
batch_size: 8
seed: 0
num_workers: 8
ckpt: null # Used for resuming from checkpoint
xfer_dir: assets/
save_last: false
save_every_n_min: 360 # keep a checkpoint every 6 hours
save_every_n_steps: null
monitor_fad: false

trainer:
  check_val_every_n_epoch: 10
  # Max iterations
  max_steps: 2000000

# Output directory
hydra:
  job:
    chdir: true
    config: 
      override_dirname: 
        kv_sep: "-"
        item_sep: "_"
  run:
    dir: logs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${name}/multirun_${now:%Y-%m-%d_%H-%M-%S}
    # subdir: ${hydra.job.override_dirname}
    subdir: ${hydra.job.num}

# name of stat to use as monitor for optuna multirun or saving checkpoints
# ex.) "val_0/mel" - Mel loss of 0th validation dataset
# null saves latest
monitor: null

hparams: []